### ISSUE TITLE
Cannot find ./lib/validator 

### ISSUE THREAD

**Issue by ameypachpute** [mkoryak/address-validator#12]
Tried using this api but gives following error.

Cannot find ./lib/validator

**Comment by AndrejGajdos** [comment]
+1

**Comment by mkoryak** [comment]
did you get it from npm?

because if you did not, you will need to run the build script manually:

```
"scripts": {
    "build": "rm -rf ./lib && coffee --compile --output lib/ src/",
    "prepublish": "npm run build",
    "test": "coffee test/test.coffee"
  },
```

so, `npm run build` and you must have coffee-script installed globally.

But better yet, just grab it from npm.

**Comment by danboy** [comment]
I get this error too after `npm install address-validator --save`

what npm pulled down doesn't have src, just:
index.js  node_modules  package.json  README.md

package.json shows "_id": "address-validator@0.2.2"

**Comment by mkoryak** [comment]
I just published a new version, and installed it. 

I see `index.js` and `lib/validator.js`  I have not tested it, but it should work
