### ISSUE TITLE
What are the possible values for "err" in the call back for AddressValidator.validate() ?

### ISSUE THREAD

**Issue by AManNamedGaurav** [mkoryak/address-validator#16]
I'm trying to do a null check of "err" in the callback but I'm not sure if there could be an error but I still get exact and/or inexact matches.

**Comment by mkoryak** [comment]
Take a look at the code:
https://github.com/mkoryak/address-validator/blob/master/src/validator.coffee#L236

You cannot get matches and an error at the same time. The values of error are the 2 errors I create and also any error that could be raised by the `request` lib - ie networking errors.
